### PR TITLE
change default date fields

### PR DESCRIPTION
**Pull request by jbennettufl**
This modification would remove the datecollected field formatted as a date and replace it with the DarwinCore text fields for eventDate, year, month, and day instead.

### CODE REVIEW

**Comment by jbennettufl** [comment]
This should not be merged quite yet as it will cause a breaking change for another package as pointed out here: [https://github.com/ropensci/spocc/blob/59f6b3b192cd8a7bb990aab94748f3bc7b044dac/R/plugins.r#L266](https://github.com/ropensci/spocc/blob/59f6b3b192cd8a7bb990aab94748f3bc7b044dac/R/plugins.r#L266) from the original issue which is located here: [https://github.com/iDigBio/ridigbio/issues/44](https://github.com/iDigBio/ridigbio/issues/44 ). This code uses the date to order the specimens in a list using a field formatted as a date.

**Comment by mgaynor1** [comment]
> This should not be merged quite yet as it will cause a breaking change for another package as pointed out here: https://github.com/ropensci/spocc/blob/59f6b3b192cd8a7bb990aab94748f3bc7b044dac/R/plugins.r#L266 from the original issue which is located here: #44. This code uses the date to order the specimens in a list using a field formatted as a date.


Contact spocc?

**Comment by jbennettufl** [comment]
Ok, what should I say to them?

**Comment by mgaynor1** [comment]
Here you go: https://github.com/ropensci/spocc/issues/263

**Comment by jbennettufl** [comment]
@mgaynor1 I've added some documentation about the fields and have added your contact info into the contributors list. If there is anything in there you would like to update or finalize feel free to let me know.

**Comment by mgaynor1** [comment]
Jessie - I updated the documentation to reflect that we are only updating the R function, the API has not been modified and the field is still available via the API (and the function, if it is indicated in the fields argument). I also added proper documentation for the return. I am unsure what the Darwin Core equivalent for collector and geopoint is, so these links are missing. 

I think it is ready to go.

**Pull request merged**
